### ISSUE TITLE
"null is not an object (evaluating '_ref1[0]')" error after sleep

### ISSUE THREAD

**Issue by Porco-Rosso** [bonus-tm/uebersicht-ping-history.widget#3]
Hi again!
I am using the widget, and every time after I put my laptop to sleep I am faced with this error message upon returning:
"null is not an object (evaluating '_ref1[0]')"

Is there anyway to implement some sort of error handling? Right now I have to manually refresh all the ubersicht widgets to get it to work again.
Thanks!

**Comment by bonus-tm** [comment]
Thank you for reporting bugs!
I think, this happens when internet connection is down. I also see this message from time to time, but as I use desktop, it occurs rarely and doesn't bother me enough to fix it. Now will try to do something with it.

**Comment by bonus-tm** [comment]
Fixed.
