### ISSUE TITLE
onclick function

### ISSUE THREAD

**Issue by SgtBauerFR** [bonus-tm/uebersicht-ping-history.widget#5]
Hi, I would like to clic on the name in order to open a ssh term.

I try to add line 69
$(domEl).find('.name').on 'click', =>@run('open http://test.com')

it work but not with a variable like

$(domEl).find('.name').on 'click', =>@run('open ssh://#{domain}')

Thank you for any help you can offer

**Comment by bonus-tm** [comment]
Maybe you should use double quotes, like this: `@run("open ssh://#{domain}")`.

[Strings in coffee script](https://coffeescript.org/#strings).

**Comment by SgtBauerFR** [comment]
I think #domain doesn't contain the domains names like #name contain the aliases names.

I get nothing with:
@run("open ssh://#{domain}") ->  terminal don't open

and if I try with
@run("open ssh://#{name}") -> the terminal open empty
@run("open http://#{name}") -> safari open a localhost tab

**Comment by SgtBauerFR** [comment]
I replace :
`@run("open http://#{name}"`

with:
`<td class="name"><a class="url" href="http://#{name}">#{name}</a></td>`

now everything works well except that I want :

`<td class="name"><a class="url" href="ssh://#{domain}">#{name}</a></td>`


how can I get the "declare -a domains" in a variable like $name ?

**Comment by bonus-tm** [comment]
Found quick and easy way to get separate values — put them both into output and parse from there. See latest changes. But links you should insert again yourself. Maybe you can make links optional and create pull request?

Anyway, thanks for feedback!
